### ISSUE TITLE
Implement JSDocs

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/dev-journal#115]
**Feature Description**
We will be updating JS function header comments to be following the JSDocs format. Implement JSDocs

Requirements/steps:
 - [x] Use JSDocs to generate documentation

**Collaborate With**
The group doing JS cleanup, potentially help out with updating comments.

**Comment by danwyl** [comment]
Using Eshas work as a jumping off point for JSDocs, I was able to have the JSDocs action run, and now uploaded to a cloudflare site.

**Comment by danwyl** [comment]
Can be found here:
https://docs-dev-journal.pages.dev/

and dev can be found (once the code is merged in)
https://dev.docs-dev-journal.pages.dev/

the main page will be documentation generated from `main` branch, while dev will be for the `dev` branch.

**Comment by danwyl** [comment]
I also think that we should separate out the implementation and the actual changing of code into two issues, given that they scope very differently.

**Comment by danwyl** [comment]
Removed requirement to change code - see #122 instead.
