### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by 04sravya** [cse110-sp24-group23/dev-journal#19]
**Feature Description**
As a user, I want to be able to easily navigate to and from different pages.

We want links to:
- Calendar page
- Daily Log
- Notes page

**Comment by ravishende** [comment]
We may want to change the style for the phone screen width to put the navbar at the top. If we go in calendar and make it the size of a phone, you have to scroll sideways to see some of the days, which can be clunky to interact with.
