### ISSUE TITLE
Missing Days of the Week Background 

### ISSUE THREAD

**Issue by brooke-tru** [cse110-sp24-group23/dev-journal#62]
**Describe the bug**
- The background color of the days of the week row is no longer dark blue. 

**Potential Solution, if known**
- Fix the CSS of the calendar.

**Comment by ravishende** [comment]
If this is fully fixed now, feel free to close the issue. Bug reports don't need to go through the same `open -> in progress -> ready to test -> done -> close issue` workflow that features do.
