### ISSUE TITLE
Daily Log

### ISSUE THREAD

**Issue by danwyl** [cse110-sp24-group23/dev-journal#8]
**Feature Description**
As a user, I want to be able to log my daily accomplishments and whatever other information I want to take down for the day.

Namely, we want to have:
- Different Editable Sections
- Save User Inputted Text in Database (Or localStorage)
- Use of a Markdown Editor for the underlying text wrangling

**Sub-Issues**
- [x] #9
- [x] #10
- [x] #11

**Comment by danwyl** [comment]
Moving to next sprint

**Comment by ravishende** [comment]
Looking at it in dev, I think it is counterintuitive to have the submit button at the top of the page rather than the bottom. You scroll down while editing a note, finally it comes time to submit and you have to scroll back up to the top.
