### ISSUE TITLE
Style notes in notes.css

### ISSUE THREAD

**Issue by ravishende** [cse110-sp24-group23/dev-journal#89]
**Feature Description**
Make the style of the notes page match the [figma](https://www.figma.com/proto/k4QCXcDXb0VpLJg3cAsWW5/CSE-110-Work-documentation-prototype?node-id=7-5&starting-point-node-id=7%3A5&t=pIvHOYNGwyA0aXew-1)

Requirements/steps:
 - [x] give note cards alternating colors (like in figma)
     - look into using [n-th child patterns](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) with variables for colors e.g. --note-backgroundcolor1, --note-background-color2, etc.
 - [x] make the add/edit popup look like the figma
    - edit the class "note-editor" and the following ids: "note-editor-title", "note-editor-content"
 - [x] add visual transitions when creating, editing, or deleting a file so it's less jarring
     - May have to look into notes.js or collaborate with #18 for this
 - [x] add hover effects to notes (like figma - underline them to show they can be clicked on)

**Parent Issue**
#16

**Blocked By**
The changes for the notes page are not yet in dev, so when you make your new branch, make sure to pull from `#18-add-note-delete-note` to get the up-to-date notes page.

**Collaborate with**
#18

**Comment by brooke-tru** [comment]
WIP: Need to adjust sizing for different screens for the note editing
